name: Auto PR Creation (Reusable)

on:
  workflow_call:
    inputs:
      target_branch:
        required: true
        type: string
    secrets:
      SECRET_GITHUB_TOKEN:
        required: true

jobs:
  create_pr_to_uat:
    if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/uat'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Branch Name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Debug GH_TOKEN
        run: |
          if [ -z "$GH_TOKEN" ]; then
            echo "GH_TOKEN is NOT set!"
            exit 1
          else
            echo "GH_TOKEN is set correctly."
          fi
        env:
          GH_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}

      - name: Authenticate GitHub CLI
        run: gh auth status
        env:
          GH_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}

      - name: Check for Existing PR to uat
        id: check_pr
        env:
          GH_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
        run: |
          EXISTING_PR=$(gh pr list --state open --base uat --json number,headRefName --jq '.[] | select(.headRefName == "${{ env.BRANCH_NAME }}") | .number')
          echo "EXISTING_PR=$EXISTING_PR" >> $GITHUB_ENV